/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZeAGeNE6MoG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { JSX, SVGProps } from "react"

export function Hero() {
  return (
    <div>
      <section className="w-full min-h-[80vh] flex items-center justify-center bg-[#0f172a] dark:bg-[#0f172a] text-white">
        <div className="container px-4 md:px-6 py-12 md:py-24 grid gap-6 md:grid-cols-2 items-center">
          <div className="space-y-4">
            <h1 className="text-4xl md:text-6xl font-bold tracking-tight">Unleash Your Creativity</h1>
            <p className="text-lg md:text-xl text-white">
              Our platform empowers you to bring your ideas to life with cutting-edge tools and seamless collaboration.
            </p>
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Get Started
            </Link>
          </div>
          <div className="relative aspect-video overflow-hidden rounded-xl">
            <video autoPlay loop muted playsInline className="absolute inset-0 h-full w-full object-cover">
              <source src="/hero-video.mp4" type="video/mp4" />
            </video>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6 grid gap-10">
          <div className="text-center space-y-3">
            <h2 className="text-3xl md:text-4xl font-bold tracking-tighter">What Our Customers Say</h2>
            <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed">
              Hear from the people who have used our platform to bring their ideas to life.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <div className="bg-muted p-6 rounded-lg shadow-lg">
              <blockquote className="text-lg font-semibold leading-snug">
                The customer service I received was exceptional. The support\n team went above and beyond to address my
                concerns.
              </blockquote>
              <div className="mt-4 flex items-center gap-4">
                <Avatar className="w-10 h-10 border">
                  <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-semibold">Jules Winnfield</div>
                  <div className="text-sm text-muted-foreground">CEO, Acme Inc</div>
                </div>
              </div>
            </div>
            <div className="bg-muted p-6 rounded-lg shadow-lg">
              <blockquote className="text-lg font-semibold leading-snug">
                The platform is incredibly intuitive and easy to use. I was\n able to get my project up and running in
                no time.
              </blockquote>
              <div className="mt-4 flex items-center gap-4">
                <Avatar className="w-10 h-10 border">
                  <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-semibold">Mia Khalifa</div>
                  <div className="text-sm text-muted-foreground">Freelance Designer</div>
                </div>
              </div>
            </div>
            <div className="bg-muted p-6 rounded-lg shadow-lg">
              <blockquote className="text-lg font-semibold leading-snug">
                I was able to scale my business with ease thanks to the\n platforms robust infrastructure and tools.
              </blockquote>
              <div className="mt-4 flex items-center gap-4">
                <Avatar className="w-10 h-10 border">
                  <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-semibold">Dwayne Johnson</div>
                  <div className="text-sm text-muted-foreground">CEO, Rock Inc</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="fixed bottom-4 right-4 z-50">
        <Card className="w-full max-w-md">
          <CardHeader className="flex flex-row items-center">
            <div className="flex items-center space-x-4">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" alt="Image" />
                <AvatarFallback>OM</AvatarFallback>
              </Avatar>
              <div>
                <p className="text-sm font-medium leading-none">Sofia Davis</p>
                <p className="text-sm text-muted-foreground">m@example.com</p>
              </div>
            </div>
            <Button size="icon" variant="outline" className="ml-auto rounded-full">
              <PlusIcon className="w-4 h-4" />
              <span className="sr-only">New message</span>
            </Button>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm ml-auto bg-primary text-primary-foreground">
                Hi, how can I help you today?
              </div>
              <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-muted">
                Hello, I&apos;m having some trouble accessing my account. Can you help me?
              </div>
              <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm ml-auto bg-primary text-primary-foreground">
                Of course! Could you please provide me with your account number?
              </div>
              <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-muted">
                Sure, it&apos;s 123456789.
              </div>
            </div>
          </CardContent>
          <CardFooter>
            <form className="flex items-center w-full space-x-2">
              <Input id="message" placeholder="Type your message..." className="flex-1" autoComplete="off" />
              <Button type="submit" size="icon">
                <SendIcon className="w-4 h-4" />
                <span className="sr-only">Send</span>
              </Button>
            </form>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}

function PlusIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SendIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
